error.internal=An internal error has occurred. Please try again later.
auth.login.failed=Unable to authenticate user {0}. Please check your credentials and try again.